version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install MySQL Client
          command: |
            sudo apt-get update
            sudo apt-get install mysql-client-core-5.7
      - run:
          name: Build the REDCap Image
          command: |
            git clone --branch redcap-cypress https://github.com/aldefouw/redcap_docker
      - run:
          name: Get REDCap Source
          command: |
            git clone --branch redcap-cypress https://github.com/aldefouw/redcap_source www
      - run:
          name: Start Docker REDCap Container
          command: |
            cd redcap_docker
            docker-compose up -d --build
      - run:
          name: Configure Cypress environment
          command: |
            cd /home/circleci/project
            sed s/PID/$PROJECT_ID/g cypress.json.example > cypress.json
            mv cypress.env.json.example cypress.env.json              
      - run:      
          name: Install Cypress and Run Tests
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use stable
            npm install
            npx cypress run --record --key $RECORD_KEY
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        context: REDCap Tests